# Default gradle parameters.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Fabric Properties.
# https://fabricmc.net/develop/
minecraft_version=26.1.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties.
mod_group=eu.pintergabor.signeditlite
mod_id=signeditlite
mod_version=1.0.12

# Dependencies.

# https://fabricmc.net/develop/
fabric_version=0.145.4+26.1.1

# https://linkie.shedaniel.me/dependencies
cloth_config_version = 26.1.154
modmenu_version = 18.0.0
